export enum SOCKET_EVENTS {
  JOIN_QUE = "JOIN_QUE",
  UPDATE_ROOM = "UPDATE_ROOM",
  UPDATE_PLAYER_PROGRESS = "UPDATE_PLAYER_PROGRESS",
  ROOM_EXPIRED = "ROOM_EXPIRED",
  WORD_COMPLETED = "WORD_COMPLETED",
  UPDATE_TIME_TO_START = "UPDATE_TIME_TO_START",
  START_MATCH = "START_MATCH",
}
export enum ROOM_STATES {
  WAITING,
  STARTED,
}
