export enum SOCKET_EVENTS {
  JOIN_QUE = "JOIN_QUE",
  COUNTDOWN_START = "COUNTDOWN_START",
  UPDATE_ROOM = "UPDATE_ROOM",
  ROOM_EXPIRED = "ROOM_EXPIRED",
}
export enum ROOM_STATES {
  WAITING,
  LOCKED,
  STARTED,
}
