export enum SOCKET_EVENTS {
  JOIN_QUE = "JOIN_QUE",
  UPDATE_ROOM = "UPDATE_ROOM",
  ROOM_EXPIRED = "ROOM_EXPIRED",
  WORD_COMPLETED = "WORD_COMPLETED",
}
export enum ROOM_STATES {
  WAITING,
  STARTED,
}
